baseURL: 'https://docs.xiv.zone/'
copyright: 'This content is licensed under a Creative Commons Attribution-ShareAlike 4.0.'
defaultContentLanguage: 'en'
disableHugoGeneratorInject: true
enableRobotsTXT: true
languageCode: 'en-us'
summarylength: 30

markup:
  tableOfContents:
    ordered: true
    startLevel: 1
  goldmark:
    parser:
        wrapStandAloneImageWithinParagraph: false

title: 'XIV Docs'
theme: 'mytheme'
timeZone: 'UTC'
paginate: 20
